const INCREMENT_LAST_ARRAY_ELEM = 'INCREMENT_LAST_ARRAY_ELEM';
const ADD_MOVIE = 'ADD_MOVIE';
const RESET_MOVIES = 'RESET_MOVIES';

export default {
   INCREMENT_LAST_ARRAY_ELEM,
   ADD_MOVIE,
   RESET_MOVIES
};
